
const companies:{[name:string]:string} = {
PETR: "Petrobras",
ITUB: "Itau Unibanco",
ITSA: "Itausa",
TIMS: "Tim",
BRDT: "Petrobras Br",
CMIG: "Cemig",
TIMP: "Tim Part S/A",
GGBR: "Gerdau",
GOAU: "Gerdau Met",
CYRE: "Cyrela Realt",
PSSA: "Porto Seguro",
RDOR: "Rede D Or",
UGPA: "Ultrapar",
LREN: "Lojas Renner",
ENEV: "Eneva",
TAEE: "Taesa",
SAPR: "Sanepar",
ELPL: "Eletropaulo",
MGLU: "Magaz Luiza",
SULA: "Sul America",
USIM: "Usiminas",
CPRE: "Cpfl Renovav",
FRRN: "All Norte",
MRVE: "Mrv",
MDIA: "M.Diasbranco",
EQMA: "Eqtlmaranhao",
ENMT: "Energisa Mt",
RENT: "Localiza",
SMLS: "Smiles",
REDE: "Rede Energia",
NTCO: "Natura",
MRSA: "Mrs Logist",
SMTO: "Sao Martinho",
MULT: "Multiplan",
DTEX: "Duratex",
ENAT: "Enauta Part",
SLCE: "Slc Agricola",
GRND: "Grendene",
QUAL: "Qualicorp",
ALSO: "Alianscsonae",
MPLU: "Multiplus",
CEGR: "Ceg",
CSRN: "Cosern",
GMAT: "Grupo Mateus",
GNDI: "Intermedica",
JSLG: "Jsl",
SUZB: "Suzano Papel",
NEMO: "Suzano Hold",
MYPK: "Iochp-Maxion",
LEVE: "Metal Leve",
ODPV: "Odontoprev",
RAIL: "Rumo S.A.",
TUPY: "Tupy",
COCE: "Coelce",
GEPA: "Ger Paranap",
SIMH: "Simpar",
CAML: "Camil",
COGN: "Cogna On",
JPSA: "Jereissati",
LAME: "Lojas Americ",
RAPT: "Randon Part",
WIZS: "Wiz S.A.",
BMGB: "Banco Bmg",
JBSS: "Jbs",
PRIO: "Petrorio",
CURY: "Cury S/A",
SEER: "Ser Educa",
EMAE: "Emae",
JHSF: "Jhsf Part",
POMO: "Marcopolo",
WHRL: "Whirlpool",
CRPG: "Cristal",
ROMI: "Inds Romi",
CEAB: "Cea Modas",
LIGT: "Light S/A",
MOVI: "Movida",
VULC: "Vulcabras",
TRIS: "Trisul",
DIRR: "Direcional",
SBFG: "Centauro",
EUCA: "Eucatex",
PTBL: "Portobello",
BKBR: "Bk Brasil",
CCPR: "Cyre Com-Ccp",
PARD: "Ihpardini",
WSON: "Wilson Sons",
TGMA: "Tegma",
CEBR: "Ceb",
LLIS: "Le Lis Blanc",
VLID: "Valid",
CCRO: "Ccr Sa",
NAFG: "Nadir Figuei",
DOHL: "Dohler",
BOAS: "Boa Vista",
SHUL: "Schulz",
OFSA: "Ourofino S/A",
PATI: "Panatlantica",
MOSI: "Mosaico",
GBIO: "Biotoscana",
HBOR: "Helbor",
VALE: "Vale S/A",
IGTA: "Iguatemi",
BRML: "BR Malls",
};

export default companies
